[project]
name = "game"
version = "0.1.0"
description = "Our first game"
readme = "README.md"
requires-python = ">=3.12.2"
dependencies = [
    "pyxel>=2.2.10",
]

[dependency-groups]
dev = [
    "ruff>=0.9.0",
]
